language: node_js
node_js:
- '4.1'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app:
    master: eversea-staging
  api_key:
    secure: Ozy4DdRWHUCqaHAffWgvbm/H/PjZTHSgRxQNOkxARaOka2t7+NlodIgy81RAqkezXkrOY1j0B0Ur4xQYqweqGeI6GscK42lHZ7yrQUceWPiRCOfMEdaw9NluFDqdX3e5XhPGe3yusek0jTDe/gJsZBJDliLiXDSP8Ehkv+Xa2HQJLjhbnfFPoeeh9vSAJfrFeSjcLepPdBGXkyDJnHTdQAH/Qr+/KjT7al+h6tEb4nJFCpU/cTuRwws9LMZ6JKS9hLqEM8Ll/0w7S9fZHfF8pvFpXZrXt8ma06stVOYmY6D8u1cJfrOzNiRBIKDgp3J6RIBNrzXbxV0YIlD5ZaLEZCDmFIOWYwankqkLbKqKYESBlKWj7F3J2z2qsCW0koLLgZBtdHDxYZioRVKrYwSefmX4xSxp9LfXs8hRhNu/ufGE1PrCa4tSR+M/CEXqtA8bOkJrcbs113QDznbpiH77mYABvcKOTWD4MPHPmbxnoaSJXTAnUfcy2X2XndOW9WjJjyqxG3DqISE301SkNb9a97fyc3GJtUwffZnoclBKBOq34mQiWSVi8DgWGz2h5iKa8IUdgAcJhsK3fZ70FVaOvAwsobMgvZafzWX7TNHZkBr2aYT04bwIAsDU/AO4N2Tqg0gPPFln0hmqzRP9ydB8mVwjWCV9XsB7MC3bYSqvCVY=
